# Generated by Django 4.2.6 on 2023-12-19 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=64, unique=True)),
                ('saldo', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrição', models.CharField(max_length=64, unique=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.conta')),
            ],
        ),
    ]
